
-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet

return {
  Telescope = "",
  ActiveLSP = "",
  ActiveTS = "綠",
  BufferClose = "",
  DapBreakpoint = "",
  DapBreakpointCondition = "",
  DapBreakpointRejected = "",
  DapLogPoint = ".>",
  DapStopped = "",
  DefaultFile = "",
  Diagnostic = "裂",
  DiagnosticError = "",
  DiagnosticHint = "",
  DiagnosticInfo = "",
  DiagnosticWarn = "",
  Ellipsis = "…",
  FileModified = "",
  FileReadOnly = "",
  FolderClosed = "",
  FolderEmpty = "",
  FolderOpen = "",
  Git = "",
  GitAdd = "",
  GitBranch = "",
  GitChange = "",
  GitConflict = "",
  GitDelete = "",
  GitIgnored = "◌",
  GitRenamed = "➜",
  GitStaged = "✓",
  GitUnstaged = "✗",
  GitUntracked = "★",
  LSPLoaded = "",
  LSPLoading1 = "",
  LSPLoading2 = "",
  LSPLoading3 = "",
  MacroRecording = "",
  NeovimClose = "",
  Paste = "",
  Search = "",
  Selected = "❯",
  Spellcheck = "暈",
}